name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Update tiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: MarkXplorer
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"
